import { BRAND_GOLD, L_BODY, L_FLOURISH } from "./paths";

const generatedHeader = "<!-- Generated by `bun scripts/generate-brand.ts`. Do not edit. -->";

const appIconBackground = "#f2e8d0";

export function renderFavicon() {
  return `${generatedHeader}
<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 541 541" fill="${BRAND_GOLD}"><g transform="translate(36 0)"><path d="${L_BODY}"/></g></svg>
`;
}

export function renderAppIcon() {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="-122 -84 712 712"><rect x="-122" y="-84" width="712" height="712" fill="${appIconBackground}"/><g fill="${BRAND_GOLD}"><path d="${L_BODY}"/><path d="${L_FLOURISH}"/></g></svg>`;
}

export const faviconPath = "public/favicon.svg";

export const rasterIcons = [
  { path: "public/favicon-32.png", svg: renderFavicon, size: 32 },
  { path: "public/apple-touch-icon.png", svg: renderAppIcon, size: 180 },
] as const;
