/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GGroupIdRouteImport } from './routes/g.$groupId'
import { Route as SShareTokenRouteImport } from './routes/s.$shareToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupIdRoute = GGroupIdRouteImport.update({
  id: '/g/$groupId',
  path: '/g/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareTokenRoute = SShareTokenRouteImport.update({
  id: '/s/$shareToken',
  path: '/s/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/s/$shareToken': typeof SShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/s/$shareToken': typeof SShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/s/$shareToken': typeof SShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/imprint' | '/privacy' | '/terms' | '/g/$groupId' | '/s/$shareToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/imprint' | '/privacy' | '/terms' | '/g/$groupId' | '/s/$shareToken'
  id:
    | '__root__'
    | '/'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/g/$groupId'
    | '/s/$shareToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  GGroupIdRoute: typeof GGroupIdRoute
  SShareTokenRoute: typeof SShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupId': {
      id: '/g/$groupId'
      path: '/g/$groupId'
      fullPath: '/g/$groupId'
      preLoaderRoute: typeof GGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareToken': {
      id: '/s/$shareToken'
      path: '/s/$shareToken'
      fullPath: '/s/$shareToken'
      preLoaderRoute: typeof SShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  GGroupIdRoute: GGroupIdRoute,
  SShareTokenRoute: SShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
